#!/usr/bin/env python3

symbols = (
	('mus_boss', 0x81),
	'mus_continue',
	'mus_credits',
	'mus_drowning',
	'mus_emerald',
	'mus_ending',
	'mus_extralife',
	'mus_fadeout',
	'mus_fz',
	'mus_gameover',
	'mus_ghz',
	'mus_gotthroughact',
	'mus_invincibility',
	'mus_lz',
	'mus_model',
	'mus_mz',
	'mus_outwater',
	'mus_reset',
	'mus_sbz',
	'mus_sega',
	'mus_shoesoff',
	'mus_shoeson',
	'mus_slz',
	'mus_ss',
	'mus_stop',
	'mus_syz',
	'mus_title',
	'mus_towater',
	('sfx_actionblock', 0xA0),
	'sfx_airding',
	'sfx_basaran',
	'sfx_bigring',
	'sfx_bonus',
	'sfx_bosshit',
	'sfx_break',
	'sfx_bubble',
	'sfx_bumper',
	'sfx_buzzexplode',
	'sfx_chain',
	'sfx_collapse',
	'sfx_continue',
	'sfx_dash',
	'sfx_death',
	'sfx_diamonds',
	'sfx_door',
	'sfx_drown',
	'sfx_electricity',
	'sfx_enterss',
	'sfx_explode',
	'sfx_flame',
	'sfx_goal',
	'sfx_jump',
	'sfx_lamppost',
	'sfx_lava',
	'sfx_lavaball',
	'sfx_pushblock',
	'sfx_register',
	'sfx_ringright',
	'sfx_roll',
	'sfx_rumble',
	'sfx_saw',
	'sfx_shield',
	'sfx_signpost',
	'sfx_skid',
	'sfx_smash',
	'sfx_spikemove',
	'sfx_splash',
	'sfx_spring',
	'sfx_stomp',
	'sfx_switch',
	'sfx_waterfall',
	'sfxcount',
	'sfxoff',
)

value = 0

for definition in symbols:
	if isinstance(definition, tuple):
		label, value = definition
	else:
		label = definition
		value += 1

	print(f'{label}: equ	${value:x}')

